/* eslint-disable */
// @ts-nocheck
// This file was automatically generated by TanStack Router.
import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRolRouteImport } from './routes/_authenticated/rol'
import { Route as AuthenticatedHojaRouteImport } from './routes/_authenticated/hoja'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMatchRoleIdRouteImport } from './routes/_authenticated/match.$roleId'

const LoginRoute = LoginRouteImport.update({ id: '/login', path: '/login', getParentRoute: () => rootRouteImport } as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({ id: '/_authenticated', getParentRoute: () => rootRouteImport } as any)
const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const AuthenticatedRolRoute = AuthenticatedRolRouteImport.update({ id: '/rol', path: '/rol', getParentRoute: () => AuthenticatedRoute } as any)
const AuthenticatedHojaRoute = AuthenticatedHojaRouteImport.update({ id: '/hoja', path: '/hoja', getParentRoute: () => AuthenticatedRoute } as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({ id: '/documentos', path: '/documentos', getParentRoute: () => AuthenticatedRoute } as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({ id: '/app', path: '/app', getParentRoute: () => AuthenticatedRoute } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({ id: '/admin', path: '/admin', getParentRoute: () => AuthenticatedRoute } as any)
const AuthenticatedMatchRoleIdRoute = AuthenticatedMatchRoleIdRouteImport.update({ id: '/match/$roleId', path: '/match/$roleId', getParentRoute: () => AuthenticatedRoute } as any)

export interface FileRoutesByFullPath { '/': typeof IndexRoute; '/login': typeof LoginRoute; '/admin': typeof AuthenticatedAdminRoute; '/app': typeof AuthenticatedAppRoute; '/documentos': typeof AuthenticatedDocumentosRoute; '/hoja': typeof AuthenticatedHojaRoute; '/rol': typeof AuthenticatedRolRoute; '/match/$roleId': typeof AuthenticatedMatchRoleIdRoute }
export interface FileRoutesByTo { '/': typeof IndexRoute; '/login': typeof LoginRoute; '/admin': typeof AuthenticatedAdminRoute; '/app': typeof AuthenticatedAppRoute; '/documentos': typeof AuthenticatedDocumentosRoute; '/hoja': typeof AuthenticatedHojaRoute; '/rol': typeof AuthenticatedRolRoute; '/match/$roleId': typeof AuthenticatedMatchRoleIdRoute }
export interface FileRoutesById { __root__: typeof rootRouteImport; '/': typeof IndexRoute; '/_authenticated': typeof AuthenticatedRouteWithChildren; '/login': typeof LoginRoute; '/_authenticated/admin': typeof AuthenticatedAdminRoute; '/_authenticated/app': typeof AuthenticatedAppRoute; '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute; '/_authenticated/hoja': typeof AuthenticatedHojaRoute; '/_authenticated/rol': typeof AuthenticatedRolRoute; '/_authenticated/match/$roleId': typeof AuthenticatedMatchRoleIdRoute }

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': { id: '/login'; path: '/login'; fullPath: '/login'; preLoaderRoute: typeof LoginRouteImport; parentRoute: typeof rootRouteImport }
    '/_authenticated': { id: '/_authenticated'; path: ''; fullPath: '/'; preLoaderRoute: typeof AuthenticatedRouteImport; parentRoute: typeof rootRouteImport }
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/_authenticated/rol': { id: '/_authenticated/rol'; path: '/rol'; fullPath: '/rol'; preLoaderRoute: typeof AuthenticatedRolRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/hoja': { id: '/_authenticated/hoja'; path: '/hoja'; fullPath: '/hoja'; preLoaderRoute: typeof AuthenticatedHojaRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/documentos': { id: '/_authenticated/documentos'; path: '/documentos'; fullPath: '/documentos'; preLoaderRoute: typeof AuthenticatedDocumentosRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/app': { id: '/_authenticated/app'; path: '/app'; fullPath: '/app'; preLoaderRoute: typeof AuthenticatedAppRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/admin': { id: '/_authenticated/admin'; path: '/admin'; fullPath: '/admin'; preLoaderRoute: typeof AuthenticatedAdminRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/match/$roleId': { id: '/_authenticated/match/$roleId'; path: '/match/$roleId'; fullPath: '/match/$roleId'; preLoaderRoute: typeof AuthenticatedMatchRoleIdRouteImport; parentRoute: typeof AuthenticatedRoute }
  }
}

interface AuthenticatedRouteChildren { AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute; AuthenticatedAppRoute: typeof AuthenticatedAppRoute; AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute; AuthenticatedHojaRoute: typeof AuthenticatedHojaRoute; AuthenticatedRolRoute: typeof AuthenticatedRolRoute; AuthenticatedMatchRoleIdRoute: typeof AuthenticatedMatchRoleIdRoute }
const AuthenticatedRouteChildren: AuthenticatedRouteChildren = { AuthenticatedAdminRoute, AuthenticatedAppRoute, AuthenticatedDocumentosRoute, AuthenticatedHojaRoute, AuthenticatedRolRoute, AuthenticatedMatchRoleIdRoute }
const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(AuthenticatedRouteChildren)
const rootRouteChildren = { IndexRoute, AuthenticatedRoute: AuthenticatedRouteWithChildren, LoginRoute }
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<any>()
